import { SiteSettings } from '../types';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  previewColors: string[];
  settings: Partial<SiteSettings>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'royal_gold',
    name: '👑 Royal Habesha Gold',
    description: 'Classic Ethiopian luxury with warm gold accents, ebony charcoal headers, and linen background.',
    previewColors: ['#C5A880', '#1A1A1A', '#F9F7F4', '#DC2626'],
    settings: {
      themePrimaryColor: '#C5A880',
      themeSecondaryColor: '#1A1A1A',
      themeHeaderBg: '#1A1A1A',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#F9F7F4',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#1A1A1A',
      themeCardMutedText: '#666059',
      themeCardBorderColor: '#E7E2DA',
      themeCardBadgeBg: '#DC2626',
      themeCardButtonBg: '#1A1A1A',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#1A1A1A',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#DC2626',
      themeAnnouncementBg: '#1A1A1A',
      themeAnnouncementTextColor: '#C5A880',
      themeTextPrimary: '#1A1A1A',
      themeTextMuted: '#666059',
      themeBorderColor: '#E7E2DA',
      themePresetName: 'royal_gold',
    },
  },
  {
    id: 'ethiopian_heritage',
    name: '🌿 Ethiopian Heritage',
    description: 'Vibrant Ethiopian flag gold, forest imperial green headers, burgundy accents, and warm ivory body.',
    previewColors: ['#D4AF37', '#1B4D3E', '#FAF8F5', '#800020'],
    settings: {
      themePrimaryColor: '#D4AF37',
      themeSecondaryColor: '#1B4D3E',
      themeHeaderBg: '#1B4D3E',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#FAF8F5',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#111827',
      themeCardMutedText: '#4B5563',
      themeCardBorderColor: '#E5E7EB',
      themeCardBadgeBg: '#800020',
      themeCardButtonBg: '#1B4D3E',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#1B4D3E',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#800020',
      themeAnnouncementBg: '#1B4D3E',
      themeAnnouncementTextColor: '#D4AF37',
      themeTextPrimary: '#111827',
      themeTextMuted: '#4B5563',
      themeBorderColor: '#E5E7EB',
      themePresetName: 'ethiopian_heritage',
    },
  },
  {
    id: 'emerald_luxe',
    name: '💎 Modern Emerald Luxe',
    description: 'High-end modern jewelry aesthetic featuring deep emerald green, mint highlights, and amber accents.',
    previewColors: ['#10B981', '#064E3B', '#F0FDF4', '#F59E0B'],
    settings: {
      themePrimaryColor: '#10B981',
      themeSecondaryColor: '#064E3B',
      themeHeaderBg: '#064E3B',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#F0FDF4',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#064E3B',
      themeCardMutedText: '#047857',
      themeCardBorderColor: '#A7F3D0',
      themeCardBadgeBg: '#F59E0B',
      themeCardButtonBg: '#064E3B',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#064E3B',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#F59E0B',
      themeAnnouncementBg: '#064E3B',
      themeAnnouncementTextColor: '#A7F3D0',
      themeTextPrimary: '#064E3B',
      themeTextMuted: '#047857',
      themeBorderColor: '#A7F3D0',
      themePresetName: 'emerald_luxe',
    },
  },
  {
    id: 'ebony_silk',
    name: '🌙 Midnight Obsidian Dark',
    description: 'Sleek luxury dark mode with obsidian black background, slate cards, platinum text, and sky blue highlights.',
    previewColors: ['#38BDF8', '#020617', '#090D16', '#EF4444'],
    settings: {
      themePrimaryColor: '#38BDF8',
      themeSecondaryColor: '#0F172A',
      themeHeaderBg: '#020617',
      themeHeaderTextColor: '#F8FAFC',
      themeAppBg: '#090D16',
      themeCardBg: '#1E293B',
      themeCardTextColor: '#F8FAFC',
      themeCardMutedText: '#94A3B8',
      themeCardBorderColor: '#334155',
      themeCardBadgeBg: '#EF4444',
      themeCardButtonBg: '#38BDF8',
      themeCardButtonTextColor: '#0F172A',
      themeButtonBg: '#38BDF8',
      themeButtonTextColor: '#0F172A',
      themeBadgeBg: '#EF4444',
      themeAnnouncementBg: '#020617',
      themeAnnouncementTextColor: '#38BDF8',
      themeTextPrimary: '#F8FAFC',
      themeTextMuted: '#94A3B8',
      themeBorderColor: '#334155',
      themePresetName: 'ebony_silk',
    },
  },
  {
    id: 'rose_velvet',
    name: '🌹 Rose Velvet Luxury',
    description: 'Sophisticated haute-couture palette with deep rose velvet, dark burgundy headers, and soft blush tint.',
    previewColors: ['#E11D48', '#4C0519', '#FFF1F2', '#BE123C'],
    settings: {
      themePrimaryColor: '#E11D48',
      themeSecondaryColor: '#881337',
      themeHeaderBg: '#4C0519',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#FFF1F2',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#4C0519',
      themeCardMutedText: '#9F1239',
      themeCardBorderColor: '#FECDD3',
      themeCardBadgeBg: '#BE123C',
      themeCardButtonBg: '#E11D48',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#E11D48',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#BE123C',
      themeAnnouncementBg: '#4C0519',
      themeAnnouncementTextColor: '#FECDD3',
      themeTextPrimary: '#4C0519',
      themeTextMuted: '#9F1239',
      themeBorderColor: '#FECDD3',
      themePresetName: 'rose_velvet',
    },
  },
  {
    id: 'sapphire_boutique',
    name: '🌊 Ocean Sapphire Boutique',
    description: 'Crisp, refreshing boutique aesthetic with ocean sapphire blue, dark navy header, and sunset orange badge.',
    previewColors: ['#0284C7', '#0C4A6E', '#F0F9FF', '#EA580C'],
    settings: {
      themePrimaryColor: '#0284C7',
      themeSecondaryColor: '#0C4A6E',
      themeHeaderBg: '#0F172A',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#F0F9FF',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#0F172A',
      themeCardMutedText: '#0369A1',
      themeCardBorderColor: '#BAE6FD',
      themeCardBadgeBg: '#EA580C',
      themeCardButtonBg: '#0284C7',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#0284C7',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#EA580C',
      themeAnnouncementBg: '#0C4A6E',
      themeAnnouncementTextColor: '#7DD3FC',
      themeTextPrimary: '#0F172A',
      themeTextMuted: '#0369A1',
      themeBorderColor: '#BAE6FD',
      themePresetName: 'sapphire_boutique',
    },
  },
  {
    id: 'sunset_amber',
    name: '🌅 Sunset Amber Glow',
    description: 'Warm golden amber highlights, rich espresso chocolate headers, and soft terracotta cream background.',
    previewColors: ['#F59E0B', '#451A03', '#FFFBEB', '#D97706'],
    settings: {
      themePrimaryColor: '#F59E0B',
      themeSecondaryColor: '#451A03',
      themeHeaderBg: '#451A03',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#FFFBEB',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#451A03',
      themeCardMutedText: '#B45309',
      themeCardBorderColor: '#FDE68A',
      themeCardBadgeBg: '#D97706',
      themeCardButtonBg: '#451A03',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#451A03',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#D97706',
      themeAnnouncementBg: '#451A03',
      themeAnnouncementTextColor: '#FDE68A',
      themeTextPrimary: '#451A03',
      themeTextMuted: '#B45309',
      themeBorderColor: '#FDE68A',
      themePresetName: 'sunset_amber',
    },
  },
  {
    id: 'amethyst_royal',
    name: '🍇 Amethyst Royal Atelier',
    description: 'Opulent royal purple accents, deep plum headers, lavender tints, and gold badges.',
    previewColors: ['#9333EA', '#3B0764', '#FAF5FF', '#EAB308'],
    settings: {
      themePrimaryColor: '#9333EA',
      themeSecondaryColor: '#3B0764',
      themeHeaderBg: '#3B0764',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#FAF5FF',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#3B0764',
      themeCardMutedText: '#7E22CE',
      themeCardBorderColor: '#E9D5FF',
      themeCardBadgeBg: '#EAB308',
      themeCardButtonBg: '#3B0764',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#3B0764',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#EAB308',
      themeAnnouncementBg: '#3B0764',
      themeAnnouncementTextColor: '#E9D5FF',
      themeTextPrimary: '#3B0764',
      themeTextMuted: '#7E22CE',
      themeBorderColor: '#E9D5FF',
      themePresetName: 'amethyst_royal',
    },
  },
  {
    id: 'terracotta_heritage',
    name: '🧱 Terracotta Clay Heritage',
    description: 'Rustic Ethiopian earth tones with warm terracotta orange, dark clay header, and copper badges.',
    previewColors: ['#C2410C', '#431407', '#FFFBFA', '#9A3412'],
    settings: {
      themePrimaryColor: '#C2410C',
      themeSecondaryColor: '#431407',
      themeHeaderBg: '#431407',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#FFFBFA',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#431407',
      themeCardMutedText: '#9A3412',
      themeCardBorderColor: '#FFEDD5',
      themeCardBadgeBg: '#9A3412',
      themeCardButtonBg: '#431407',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#431407',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#9A3412',
      themeAnnouncementBg: '#431407',
      themeAnnouncementTextColor: '#FFEDD5',
      themeTextPrimary: '#431407',
      themeTextMuted: '#9A3412',
      themeBorderColor: '#FFEDD5',
      themePresetName: 'terracotta_heritage',
    },
  },
  {
    id: 'platinum_ivory',
    name: '🏛️ Platinum Minimal Ivory',
    description: 'Clean high-fashion minimalist gallery aesthetic with titanium gray accents, crisp black headers, and alabaster background.',
    previewColors: ['#64748B', '#0F172A', '#F8FAFC', '#2563EB'],
    settings: {
      themePrimaryColor: '#64748B',
      themeSecondaryColor: '#0F172A',
      themeHeaderBg: '#0F172A',
      themeHeaderTextColor: '#FFFFFF',
      themeAppBg: '#F8FAFC',
      themeCardBg: '#FFFFFF',
      themeCardTextColor: '#0F172A',
      themeCardMutedText: '#475569',
      themeCardBorderColor: '#E2E8F0',
      themeCardBadgeBg: '#2563EB',
      themeCardButtonBg: '#0F172A',
      themeCardButtonTextColor: '#FFFFFF',
      themeButtonBg: '#0F172A',
      themeButtonTextColor: '#FFFFFF',
      themeBadgeBg: '#2563EB',
      themeAnnouncementBg: '#0F172A',
      themeAnnouncementTextColor: '#CBD5E1',
      themeTextPrimary: '#0F172A',
      themeTextMuted: '#475569',
      themeBorderColor: '#E2E8F0',
      themePresetName: 'platinum_ivory',
    },
  },
];
